name: 'appen'
description: 'append timestamp to Google Spread Sheet'
inputs:
  # context は共有しているようなので、今回は input にしない.
  # (github は共有していない?)
  workload-identity-provider:
    description: 'Workload Identity Provider'
    required: true
    default: ''
  service-account:
    description: 'Service Account'
    required: true
    default: ''
  run-id:
    description: 'Run ID'
    required: true
    default: ''
  min:
    description: 'Step'
    required: true
    default: ''
  spread-sheet-id:
    description: 'Spread Sheet ID'
    required: true
    default: ''
  sheet-name:
    description: 'Sheet name'
    required: true
    default: ''

runs:
  using: 'composite'
  steps:
    - name: Use Node.js 16.x
      uses: actions/setup-node@v1
      with:
        node-version: 16.x

    - name: Cache node modules
      uses: actions/cache@v2
      env:
        cache-name: cache-node-modules
      with:
        path: ~/.npm
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-

    - name: Install modules
      run: npm ci
      shell: bash

    - name: Build
      run: npm run build
      shell: bash

    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v0.6.0'
      with:
        workload_identity_provider: ${{ inputs.workload-identity-provider }}
        service_account: ${{ inputs.service-account }}

    - name: Append timestamp to Google Spread Sheet
      run: npx zx dist/index.js --run-id "${RUN_ID}" --min "${MIN}"
      env:
        RUN_ID: ${{ inputs.run-id }}
        Min: ${{ inputs.min }}
        SPREADSHEET_ID: ${{ inputs.spread-sheet-id }}
        SHEET_NAME: ${{ inputs.sheet-name }}
      shell: bash
