name: append
on:
  push:
  workflow_dispatch:
  #schedule:
  #  - cron: "3,23,43 * * * *"

jobs:
  append:
    environment: append

    permissions:
      contents: 'read'
      id-token: 'write'

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Append timestamp to Google Spread Sheeet
        uses: ./.github/actions/append
        with:
          workload-identity-provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          service-account: ${{ secrets.SERVICE_ACCOUNT }}
          step: 23
          spread-sheet-id: ${{ secrets.SPREADSHEET_ID }}
          sheet-name: ${{ secrets.SHEET_NAME }}
